name: vedavita
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4


#---------PACKAGES-------------#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #State Management
  flutter_riverpod: ^2.6.1
  http: ^1.3.0

  #Product Specific
  another_flushbar: ^1.12.30 # for creating custom message bar
  flutter_svg: ^2.1.0 
  flutter_markdown: ^0.7.7
  intl: ^0.18.1
  http_parser: ^4.0.2      # For multipart file uploads
  image_picker: ^1.1.2     # For picking images
  # path: ^1.9.1

#---------./ PACKAGES-------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

 
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

